config/routes.rb
Rails.application.routes.draw do
  root to:'pages#home'
  get 'about', to: 'pages#about'
  get 'autos', to: 'pages#autos'
  resources :contacts, only: :create
  get 'Contacto', to: 'contacts#new', as: 'new_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, confirmation: true
  validates :email_confirmation, presence: true
  validates :comments, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
       name = params[:contact][:name]
       email = params[:contact][:email]
       body = params[:contact][:comments]
       ContactMailer.contact_email(name, email, body).deliver
       flash[:success] = "Message sent."
       redirect_to new_contact_path
    else
       flash[:error] =""
       if params[:contact][:name] == ""
         flash[:error] = flash[:error] + " Porfavor ingrese su nombre."
         
       end
       if params[:contact][:email] == ""
         flash[:error] =flash[:error] + " Porfavor ingrese su correo."
        
       end
       if params[:contact][:email_confirmation] == ""
       flash[:error] =flash[:error]+ " Porfavor ingrese su correo 2 veces."
       
       end
       if params[:contact][:comments] == ""
       flash[:error] = flash[:error]+" Porfavor ingrese su consulta."
       
       end
       if params[:contact][:email_confirmation] != params[:contact][:email]
       flash[:error] =flash[:error]+ " Porfavor confirme correctamente su correo."
       
       end
       
       redirect_to new_contact_path
    end
  end
  
  private 
    def contact_params
      params.require(:contact).permit(:name, :email, :email_confirmation, :comments)
    end 
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
  
  def autos
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">Contáctanos</h3>
    <div class="col-md-4 col-md-offset-4">
      
      
      <div class="well">
        <% flash.each do |type, msg| %>
         <%= content_tag :div, msg, class: "alert alert-#{type}" %>
      <% end %>
        <%= form_for @contact do |f| %>
          <div class="form-group">
             <a>Nombre:</a>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
             <a>Correo:</a>
             <a> (a este correo llegara nuestra respuesta)</a>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <a>Repita Correo:</a>
            <%= f.text_field :email_confirmation, class: 'form-control' %>
          </div>
          <div class="form-group">
             <a>Consulta:</a>
            <%= f.text_area :comments, class: 'form-control' %>
          </div>
          <%= f.submit 'Enviar', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Villalobos</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Heebo" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
       <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            
            <%= link_to "/", class: "navbar-brand" do %>
              <i class="glyphicon glyphicon-home" aria-hidden="true" ></i>
              Inicio
            <% end %>
            
           
            </div> 

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav">
                 
                <li><%= link_to about_path do %>
                  <i class="glyphicon glyphicon-road" aria-hidden="true"></i>
                  Ubicación
                <% end %></li>
                <li><%= link_to new_contact_path do %>
                  <i class="glyphicon glyphicon-envelope" aria-hidden="true"></i>
                  Contacto
                <% end %></li>
                
              </ul>
              <ul class="nav navbar-nav navbar-right">
                <li><a href="https://www.chileautos.cl/automotrizvillalobos" target="_blank">ChileAutos</a></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Vehículos <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Autos", autos_path %></li>
                  <li><%= link_to "Camionetas", "/" %></li>
                  <li><a href="#">4 x 4</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Vehículos de trabajo</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="#">Ambulancias</a></li>
                </ul>
              </li>
               
             
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
      </nav>
         
         
    <div class="container-fluid">
       <%= yield %>
    </div>
    
        
          
      
      <nav class="navbar1 navbar-fixed-bottom">
        <div class="container-fluid" >
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
             <p class="navbar-text">Automotora Villalobos</p>
            </div>
          
             <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
                <ul class="nav navbar-nav navbar-left">
                    <div class="navbar-header">
                      <a class="navbar-brand" href="#">
                        <img alt="Brand" src="icono.jpg">
                      </a>
                    </div>

                     <div class="navbar-header">
                      <a class="navbar-brand" href="#">
                        <img alt=".." src="icono.jpg">
                      </a>
                    </div>
                  
                    <div class="navbar-header">
                      <a class="navbar-brand" href="#">
                        <img alt="Brand" src="icono.jpg">
                      </a>
                    </div>
                  
                    <div class="navbar-header">
                      <a class="navbar-brand" href="#">
                        <img alt="Brand" src="icono.jpg">
                      </a>
                    </div>
                  
                    <div class="navbar-header">
                      <a class="navbar-brand" href="#">
                        <img alt="Brand" src="icono.jpg">
                      </a>
                    </div>
                   </ul>
                  <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">REDES SOCIALES <span class="caret"></span></a>
                      <ul class="dropdown-menu">
                        <li><%= link_to "FACEBOOK", "/" %></li>
                        <li><%= link_to "TWITTER", "/" %></li>
                        <li><%= link_to "WHATSAPP", "/" %></li>
                        <li role="separator" class="divider"></li>
                        <li><%= link_to "SOMOS", "/" %></li>
                        <li role="separator" class="divider"></li>
                        <li><%= link_to "TRABAJA CON NOSOTROS", "/" %></li>
                      </ul>
                    </li>
                  </ul> 
                

             </div>
        </div>
      </nav> 
    
  
  </body>
</html>

app/views/pages/about.html.erb
<html>
 <head>
    
     
  </head>
  <body>
    <div class="col-md-8 col-md-offset-2"  style="
    margin-bottom: 150px;" >  
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1664.1675816410404!2d-70.6762613418712!3d-33.46662369519238!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x9662c4e152b77d55%3A0x7db774e4697a9e3c!2sAntofagasta+3034%2C+Santiago%2C+Regi%C3%B3n+Metropolitana!5e0!3m2!1ses-419!2scl!4v1544410675947" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
     
     <div class="panel panel-default">
       <p>Ubicación: Antofagasta 3034, Estación Central.</p>
              
        <p>Horario de Atención: Lunes a Viernes : 09:00 hrs. a 13:00 hrs. y 14:30 hrs. a 18:00 hrs.</p>
            <div class="panel-footer text-center">SEDE ESTACION CENTRAL</div>
      </div>
    </div>
    
    
      
   
    
  </body>
  
  
</html>

app/views/pages/autos.html.erb
<!DOCTYPE html>
<html>
  <head>
    
  </head>
  <body>
    
       
    
     <div class="col-md-8 col-md-offset-0">
       
       <div class="panel panel-default" >
          <div class="panel-body">
            <img src="1p.jpg" class="img-responsive" alt="Logo">
            modelos
          </div>
          
          <div class="panel-footer">SEDAN 2017, minion</div>
       </div>
    </div>
    
       <div class="col-md-8 col-md-offset-0">
       
       <div class="panel panel-default">
          <div class="panel-body">
            <img src="minions.jpg" class="img-responsive img-rounded" alt="Logo">
            modelos
          </div>
          
          <div class="panel-footer">SEDAN 2017, minion</div>
       </div>
    </div>
    
  
   
    
       
  </body>
   
     
    
  <!-- -------------- <div class="col-md-4 col-md-offset-0">
       <div class="media">
        <div class="media">
          <a href="#">
            <img class="media-object" src="4.jpg" alt="Logo" width = "360" height = "200">
          </a>
        </div>
        <div class="media-body">
          <h4 class="media-heading">Media heading</h4>
          ...
        </div>
       </div>
    </div> 
-->
 
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>

  <head>
      <h1 class="claseUno">
        OFERTAS IMPERDIBLES
      </h1>
  </head>

    
  <body>
      <div class="col-md-6 col-md-offset-0">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
       
        <div class="carousel-inner" role="listbox">
          <div class="item active" >
             <img src="1p.jpg" alt="Logo">
           <div class="carousel-caption">
              Bono $1.000.000
           </div>
          </div>
          <div class="item">
            <img src="1p.jpg" alt="Logo">
            <div class="carousel-caption">
               Bono $800.000
            </div>
          </div>
          <div class="item">
            <img src="1p.jpg" alt="Logo">
            <div class="carousel-caption">
              Bono $400.000
            </div>
          </div>
          Validez hasta agotar stock.
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>
    </div>
 <!-------------------------------------------------- otro slide --------------------------------------------------------------- -->
    <div class="col-md-6 col-md-offset-0">
      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
        <ol class="carousel-indicators">
          <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
          <li data-target="#carousel-example-generic" data-slide-to="1"></li>
          <li data-target="#carousel-example-generic" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
       
        <div class="carousel-inner" role="listbox">
          <div class="item active" >
             <img src="1p.jpg" alt="Logo">
           <div class="carousel-caption">
              Bono $1.000.000
           </div>
          </div>
          <div class="item">
            <img src="1p.jpg" alt="Logo">
            <div class="carousel-caption">
               Bono $800.000
            </div>
          </div>
          <div class="item">
            <img src="1p.jpg" alt="Logo">
            <div class="carousel-caption">
              Bono $400.000
            </div>
          </div>
          Validez hasta agotar stock.
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
    </div>
    </div>
    
   
  </body>
</html>